### ISSUE TITLE
Deleting old source maps

### ISSUE THREAD

**Issue by internettrans** [alexisvincent/systemjs-hmr#16]
I don't even know if this is possible, but one thing that would be awesome is if the source mapped files in dev tools were automatically updated with the new code. Right now what seems to happen is that the code is being hot reloaded correctly, but the source maps for the hot reloaded file still have the old code.

Is this something that others have run into? Is it even possible to get the browser to update source maps?

**Comment by alexisvincent** [comment]
Interesting, I'll look into it

Kind regards
Alexis

**Comment by alexisvincent** [comment]
Can you check if closing devtools and opening it again has the new updated source maps? I'm assuming chrome. Found an issue in chrome where they don't update.

https://bugs.chromium.org/p/chromium/issues/detail?id=438251#c21

**Comment by internettrans** [comment]
Yes, I am using chrome and I just verified that closing and re-opening the dev tools causes the source maps to be reloaded which is great. Also, doing `alt + r` to reload the dev tools works great too.

Getting the sourcemaps to be hot reloaded without closing/reopening the dev tools seems like something only Chrome dev tools could fix. I'll upvote the issue on the chromium bug, but I don't see any way how systemjs-hmr could solve this issue itself.

**Comment by alexisvincent** [comment]
Thanks, yeah :) that's helpful thanks
