### ISSUE TITLE
reload deps children

### ISSUE THREAD

**Issue by icode** [alexisvincent/systemjs-hmr#22]
```button.jsx
export default class Button extends Component 
```
```app.jsx
import Button from "button.jsx"
render(){
    return (<Button>button</Button>)
}
```

button.jsx on change app.jsx should fire reload

**Comment by alexisvincent** [comment]
@icode Which version of SystemJS?

**Comment by icode** [comment]
```
System.version
"0.20.5 Dev"
```

**Comment by alexisvincent** [comment]
You need at least v0.20.8 or v0.19.x, will add to docs.

Kind regards
Alexis




On Thu, Mar 2, 2017 at 3:23 AM +0200, "icode" <notifications@github.com> wrote:










System.version
"0.20.5 Dev"

**Comment by icode** [comment]
update systemjs is ok
