### ISSUE TITLE
Display err.originalErr

### ISSUE THREAD

**Issue by mavericken** [alexisvincent/systemjs-hmr#24]
When I get errors in my module from system hmr, the stack trace doesn't have the right source mappings.  I fixed for myself by using `err.originalErr || err` instead of just `err`.  I am not sure what the value is in having the modified broken error, if there is any.  I think we should either send originalErr only or both to the console.

**Comment by alexisvincent** [comment]
Where in the source do you mean?

**Comment by mavericken** [comment]
I haven't tried it on the current version, but looks like here would be it:
https://github.com/alexisvincent/systemjs-hmr/blob/162c167cdbac083e007b5bb57cc4b5952c1832bb/lib/index.js#L339

```
                .map(entry => System.import(entry).catch(err => {
                  _.lastImportFailed = true
                  console.error(err)  // right here, could change to err.originalErr || err
                }))
                // Print any errors
```

**Comment by mavericken** [comment]
```
                .map(entry => System.import(entry).catch(err => {
                  _.lastImportFailed = true
                  console.error(err)  // right here, could change to err.originalErr || err
                }))
                // Print any errors
```
