### ISSUE TITLE
The systemjs-hmr polyfill must be loading after SystemJS has loaded

### ISSUE THREAD

**Issue by peteruithoven** [alexisvincent/systemjs-hmr#25]
I've been a long time user of systemjs and the systemjs-hot-reloader and I'm having some problems updating to the latest version. 
I keep getting the following error:
```
The systemjs-hmr polyfill must be loading after SystemJS has loaded
```
I'm having this issue in a very basic example. Even with the following html code I'm getting this error:
``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script type="text/javascript" src="jspm_packages/system.src.js"></script>
    <script type="text/javascript" src="jspm.config.js"></script>
  </head>
  <body>
    <script type="text/javascript">
      System.import('systemjs-hot-reloader');
    </script>
  </body>
</html>
```

I'm opening the error in the systemjs-hmr project since that's where the error is coming from. 
Versions I'm using:
- jspm 0.17.0-beta.41
- SystemJS v0.20.10 Dev
- systemjs-hot-reloader 1.1.0
- systemjs-hmr 2.0.9

**Comment by peteruithoven** [comment]
systemjs-hmr [checks](https://github.com/alexisvincent/systemjs-hmr/blob/master/lib/index.js#L13) whether `System` and `systemjs` is already defined

When I add the same check index.html:
``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script type="text/javascript" src="jspm_packages/system.src.js"></script>
    <script type="text/javascript" src="jspm.config.js"></script>
  </head>
  <body>
    <script type="text/javascript">
      console.log('outside system hmr');
      console.log('  System: ', System);
      console.log('  SystemJS: ', SystemJS);
      console.log('  !System: ', !System);
      console.log('  !!SystemJS: ', !!SystemJS);
      System.import('systemjs-hot-reloader');
    </script>
  </body>
</html>
```
I get: 
```
outside system hmr
(index):12   System:  SystemJSLoader$1 {registry: Registry, trace: false, _loader: Object, scriptSrc: "http://localhost:3000/jspm_packages/system.src.js", _nodeRequire: undefined…}
(index):13   SystemJS:  SystemJSLoader$1 {registry: Registry, trace: false, _loader: Object, scriptSrc: "http://localhost:3000/jspm_packages/system.src.js", _nodeRequire: undefined…}
(index):14   !System:  false
(index):15   !!SystemJS:  true
```

So something happens to System before `systemjs-hmr` checks it.

**Comment by alexisvincent** [comment]
Looking at the check, I think I spotted a bug, it should be `!SystemJS` not `!!SystemJS`. Don't know how that got through... 

Are you able to check if this solves your issue?

**Comment by peteruithoven** [comment]
Ah... Yeah, looks like it. I changed it in the `dist/systemjs-hmr.js`, then the warning goes away and hot-reloading still works. Thanks for the quick response.

**Comment by alexisvincent** [comment]
Awesome! Will try submit a new version tonight.

**Comment by peteruithoven** [comment]
Thanks!

**Comment by alexisvincent** [comment]
Will publish once I fix your other issue. I have a suspicion it might actually be a SystemJS bug

**Comment by nonsensecreativity** [comment]
Got same issue here

- jspm@0.17.0-beta.41
- SystemJS@0.20.14
- systemjs-hot-reloader@1.1.0
- systemjs-hmr@2.0.9

**Comment by dazinator** [comment]
Raised #29 which I think might be a duplicate of this issue, however I was using systemjs 2.0 which in hindsight probably wont work, I'll try downgrading systemjs to 0.20.X
