### ISSUE TITLE
Handle circular dependencies

### ISSUE THREAD

**Issue by frederikschubert** [alexisvincent/systemjs-hmr#3]
Currently the order of reloading of a module's dependant modules is not defined by the order in which they were loaded.
This leads to errors when there is a circular dependency.
I suggest to take the order of loading into account when deleting and reloading the modules.

**Comment by alexisvincent** [comment]
Thanks for the issue. I can't look at it just yet, I'm swamped with deadlines. But will check this out on the weekend.

**Comment by alexisvincent** [comment]
Can you be more specific? It would be really helpful to see an example dependency tree.

**Comment by frederikschubert** [comment]
I will try to come up with a minimal example and ping you here!

**Comment by alexisvincent** [comment]
Any progress on this?

**Comment by frederikschubert** [comment]
I am currently occupied with my studies but will post an example on Friday.

**Comment by alexisvincent** [comment]
Great :)

**Comment by frederikschubert** [comment]
It is really difficult to come up with a minimal reproducible example for this issue. This error appears "sometimes" in our angular 2 projects. I suspect that the error is connected to how the decorators are evaluated.
One possible fix would be to reimport the modules in the order in which they were loaded the first time. As far as I understood from the code, the order of the reimports is decided by the order of `Object.keys`.
Sorry that I cannot come up with something more helpful yet.

**Comment by alexisvincent** [comment]
I need to have a good look at how this hot reloader works. I think this codebase can be greatly simplified. But I may be wrong. I'm in the process of refractoring and adding comments. So I'll be in a better place to look at this later this week. SystemJS handles circular deps according to the spec. And when I take a look at this I'm hoping it's as simple as recursively deleting modules upwards and then reimporting the root and relying on SystemJS for the rest

**Comment by frederikschubert** [comment]
Yes that would have been my approach as well. Currently the modules are deleted and reimported manually by the plugin.

The manual reimport is needed to call the `reload` hook of the deleted modules. See [here](https://github.com/alexisvincent/systemjs-hmr/blob/master/lib/index.js#L73)

**Comment by alexisvincent** [comment]
Oh I see. Checkout issue #2. Won't need that reload logic anymore

**Comment by frederikschubert** [comment]
Great!

**Comment by alexisvincent** [comment]
See #2 I pushed a rewrite of the reloader, with new unload and state hydration mechanisms. Should fix your issue.

**Comment by frederikschubert** [comment]
The rewrite looks good! I will give it a try as soon as I can and report my results here.

**Comment by alexisvincent** [comment]
Awesome, if you haven't already read the rewrite, I've added extensive documentation (as in more documentation then code I think), in the next.js file. Should be very clear how it works, I want it to be super simple to contribute.

**Comment by frederikschubert** [comment]
Yes I read through it. It is much easier to comprehend now! 👍

**Comment by alexisvincent** [comment]
Cool cool 👍. The README has been updated to explain how this works.

**Comment by frederikschubert** [comment]
~~I get the same error as https://github.com/alexisvincent/systemjs-hmr/issues/5. Using the version that is in master.~~
Seems like I was still using the old version.

**Comment by alexisvincent** [comment]
Oh, you need to import systemjs-hmr/dist/next.js

**Comment by frederikschubert** [comment]
Alright. Now I get this error when the `System.normalize` hook is called during reload:

```
TypeError: this.has is not a function
    at SystemJSLoader.coreResolve (http://localhost:3000/jspm_packages/system.src.js:1730:12)
    at SystemJSLoader.<anonymous> (http://localhost:3000/jspm_packages/system.src.js:1752:32)
    at http://localhost:3000/jspm_packages/system.src.js:2546:36
```

**Comment by alexisvincent** [comment]
Hmm. How are you testing this?

**Comment by frederikschubert** [comment]
I patched the `systemjs-hot-reloader` to use the new API. Basically I just removed the `catch` from [here](https://github.com/capaj/systemjs-hot-reloader/blob/master/hot-reloader.js#L40).
I also tried to do it via the console but I get the same error.

**Comment by alexisvincent** [comment]
How far does it get in the reload process

**Comment by frederikschubert** [comment]
The error occurs during the [normalization](https://github.com/alexisvincent/systemjs-hmr/blob/master/lib/next.js#L197). It seems that the prototype patching is not working correctly. The `this` in [this](https://github.com/systemjs/systemjs/blob/9ae69b905f93df449357310b0b53de8c3e919e17/dist/system.src.js#L1752) function has not the right prototype chain. So the call to `this.has` fails [here](https://github.com/systemjs/systemjs/blob/9ae69b905f93df449357310b0b53de8c3e919e17/dist/system.src.js#L1730).

I should also add that I am using `plugin-typescript` but that should not be a problem I guess.

**Comment by frederikschubert** [comment]
I cloned this repo and tried the test and get the same error. Which systemjs version are you using?
I am using `SystemJS v0.19.40`.

I inlined the `System.has` function and then the hot reload works. In the end `reloader.loadCache.clear();` throws an error because the `loadCache`is undefined.

**Comment by frederikschubert** [comment]
I found a fix ~~and will make a PR~~. https://github.com/alexisvincent/systemjs-hmr/pull/7

**Comment by alexisvincent** [comment]
Thanks! I also forgot, when using `_System` you need to `_System.normalize(System, "someModule")`

**Comment by alexisvincent** [comment]
Do your circular reps work now.

**Comment by frederikschubert** [comment]
Now I get this error when the modulename is normalized:

```
TypeError: CreateListFromArrayLike called on non-object
    at eval (http://localhost:3000/jspm_packages/github/alexisvincent/systemjs-hmr@master/dist/next.js:200:50)
```

**Comment by alexisvincent** [comment]
Sorry. Pushing a fix

**Comment by alexisvincent** [comment]
Pushed and published to npm

**Comment by frederikschubert** [comment]
Great! Now it works!

**Comment by alexisvincent** [comment]
Awesome :) Thoughts on the new state hydration/ unload api?

**Comment by frederikschubert** [comment]
I like it! I am not sure about the `@hot` module name but I can't come up with something better. :)

**Comment by alexisvincent** [comment]
If you come up with a better name let me know :) Do you have an opinion on the exporting state vs private persistent object state hydration techniques?

**Comment by frederikschubert** [comment]
I like the current API with the exported state. This gives the developer the freedom to implement the state re-hydration any way he/she likes.

**Comment by alexisvincent** [comment]
Cool thanks for the input.
