### ISSUE TITLE
__unload function and AMD

### ISSUE THREAD

**Issue by dazinator** [alexisvincent/systemjs-hmr#32]
I have an AMD module, however when I reload it, systemjs-hmr doesn't see the "__unload" function and so it never fires.

Here is my AMD module, perhaps I am not exporting it correctly?

```
define("ModuleA", ["require", "exports", "@hot"], function (require, exports, module) {
    "use strict";

    var self = {};
    self.addModuleToList = function (listId, moduleName) {
        var ul = document.getElementById(listId);
        var li = document.createElement("li");
        li.appendChild(document.createTextNode(moduleName + " Loaded.. I am productive!"));
        ul.appendChild(li);      
    };

    self._state = module ? module._state : {};
    self.addModuleToList("modules", "ModuleA");
    var unload = () => {
        console.log('Unload something (unsubscribe from listeners, disconnect from socket, etc...)');
    };

    self.__unload = unload;


    exports.__unload = () => {
        console.log('Unload something (unsubscribe from listeners, disconnect from socket, etc...)')
        // force unload React components
    };

    return self;

});

```

Debugging a `reload` the issue occurs here:

```
 if (typeof module.__unload == 'function') module.__unload();
```

Basically, `module` at this point doesnt have any `unload()` function - it looks like this in the console:

```
module
j {Symbol(): {…}}

```

However what does work is:

`module.default.__unload`

Is this caused by the way I am exporting this function? (If so, what is the correct way?) ~~or do you think this might just be a systemjs change? (if so I'll include the fix mentioned above in my PR)~~ 
Also tried with systemjs `0.20.19` and the same problem occurred, making me think it must be more down to my AMD definition and me not guessing the correct way to export this unload function!

**Comment by dazinator** [comment]
AHA so it does work with an older systemjs version:
https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.47/system.js

So this must have been broken by a system.js release somewhere between 0.19.47 and 0.20.19.
When getting a module from the registry, all of sudden the module now has this "default" property and the exported functions are on there.
I'll try and do the tedious work to figure out which version it was broken in, and then submit a PR with the fix by checking if that systemjs version is in use (or greater).

**Comment by alexisvincent** [comment]
🎉 I’m super chuffed that this stuff is getting looked at! I’ve felt pretty guilty about not being able to give this project/ecosystem the attention it deserves

**Comment by dazinator** [comment]
@alexisvincent Don't worry, I kind of know that feeling :-)
Thanks for being responsive and helping out with questions though it's much appreciated.
