### ISSUE TITLE
Question with @hot

### ISSUE THREAD

**Issue by dazinator** [alexisvincent/systemjs-hmr#36]
I was wondering, given that @hot is mapped to `@empty` - how / where does this get set to an actual instance of the old module when the module is reloaded? Is this something that systemjs-hmr does?

**Comment by alexisvincent** [comment]
@hot is only mapped to empty in production mode, along with the rest of systemjs-home. During normal reloads the logic is handled in the resolveHotModule function used on line 325

**Comment by alexisvincent** [comment]
https://github.com/alexisvincent/systemjs-hmr/blob/master/lib/util.ts#L329

**Comment by dazinator** [comment]
Thanks :-)
