### ISSUE TITLE
Module was not found in Systemjs moduleRecords

### ISSUE THREAD

**Issue by jjrv** [alexisvincent/systemjs-hmr#5]
capaj/systemjs-hot-reloader sometimes sends change events for files that weren't (yet) loaded as part of the application. Then [this line](https://github.com/alexisvincent/systemjs-hmr/blob/1ab2f45f55e1ad16785fccc3f1ba4fa3a2fb1905/lib/index.js#L32) throws an error. I added `.catch((err: any) => false)` on [this line](https://github.com/alexisvincent/systemjs-hmr/blob/1ab2f45f55e1ad16785fccc3f1ba4fa3a2fb1905/lib/index.js#L166) to fix it but not sure if that's the best way to handle it.

**Comment by alexisvincent** [comment]
I'm in the process of refactoring this code base. Will take this into account when I get here :) Thanks for the issue

**Comment by jjrv** [comment]
It works now.

**Comment by jjrv** [comment]
Oops spoke too soon. The same issue and some related ones are still in the `next` version...

**Comment by alexisvincent** [comment]
Thanks :)
