### ISSUE TITLE
Use Trace.API in SystemJS 20 and SystemJS.defined in 19 (current)

### ISSUE THREAD

**Issue by alexisvincent** [alexisvincent/systemjs-hmr#6]
@guybedford

What can I rely on SystemJS.defined to provide?

**Comment by alexisvincent** [comment]
@guybedford ping

**Comment by guybedford** [comment]
@alexisvincent it is what you see :) There's no spec anywhere, just https://github.com/systemjs/systemjs/blob/master/lib/register.js#L20.

**Comment by alexisvincent** [comment]
@guybedford Thanks, my question was badly phrased. 

In light of this issue [Trace API](https://github.com/capaj/systemjs-hot-reloader/issues/94), is it fine to use System.defined? As in this is the way you plan to move forward? :)

**Comment by guybedford** [comment]
It's the way to work with it in this version of systemjs. In the next major
the trace api will be reliable again and defined won't be available.

**Comment by alexisvincent** [comment]
Ok, thanks. Which version will it be deprecated in? 20?

**Comment by guybedford** [comment]
Yeah, and then replaced with the trace API from https://github.com/ModuleLoader/es-module-loader#tracing-api.

**Comment by alexisvincent** [comment]
Great thanks. Just to clarify. Will it be deprecated or removed in 20?

**Comment by guybedford** [comment]
Removed.

**Comment by alexisvincent** [comment]
Supported in latest build, pending https://github.com/ModuleLoader/es-module-loader/issues/532
